name: Publish to PyPI

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Print release event details (debug)
        run: |
          echo "Release Tag: ${{ github.event.release.tag_name }}"
          echo "Release Name: ${{ github.event.release.name }}"
          echo "Release Body: ${{ github.event.release.body }}"
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist/ 
      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.12.3