name: Publish to PyPI

on:
  workflow_run:
    workflows: ["Build and Release"]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Hatch
        run: pip install hatch

      - name: Build
        run: hatch build

      # - name: Download build artifact - can't get this to work
      #   uses: actions/download-artifact@v4
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     name: dist
      #     path: ./dist/ 
      
      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.12.3