name: Build and Release Python Wheel

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    if: contains(github.event.head_commit.message, 'release')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Hatch
        run: pip install hatch

      - name: Build the wheel
        run: hatch build

      - name: Create a Release
        run: |
          gh --version
          RELEASE_DATE=$(date +'%Y-%m-%d')
          gh release create "v${RELEASE_DATE}" dist/affinity-*.whl --title "Release ${RELEASE_DATE}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add latest tag
        run: |
          git tag -f latest
          git push origin latest --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}