name: Build and Release Python Wheel

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    if: contains(github.event.head_commit.message, 'release')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Hatch
        run: pip install hatch

      - name: Build
        run: hatch build

      - name: Create a Release
        run: |
          VERSION=$(cat pyproject.toml | grep version | cut -d'"' -f2)
          RELEASE_DATE=$(date +'%Y-%m-%d')
          RELEASE_TITLE="Release ${VERSION} (${RELEASE_DATE})"
          
          gh release create "${VERSION}" dist/* -t "${RELEASE_TITLE}" --latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload built package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/ 